2024-11-08T12:34:46 {"cpu": 0.09375, "cpu_total": 16, "cpu_usage": 0.005859375, "memory": 2612.0, "memory_total": 9688.0, "memory_usage": 0.2696118909991742, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1731069286.754371, "uuid": "2c77d79f39a6493293ce1438afd2a157"}
2024-11-08T12:34:46 {"block_run_id": 1, "block_uuid": "load_order_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline retail_pipeline block load_order_data", "timestamp": 1731069286.965844, "uuid": "b6eaa4bc281740a093eb8ba2888581ba"}
2024-11-08T12:34:46 {"cpu": 0.09375, "cpu_total": 16, "cpu_usage": 0.005859375, "memory": 2651.0, "memory_total": 9688.0, "memory_usage": 0.2736374896779521, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1731069286.966869, "uuid": "bf4b1feec77f42589c363e43e1bd26e2"}
2024-11-08T12:34:48 {"block_run_id": 3, "block_uuid": "load_marketing_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 3: pipeline retail_pipeline block load_marketing_data", "timestamp": 1731069288.037748, "uuid": "db0dac253154491198d75e75811fcbeb"}
2024-11-08T12:34:48 {"block_run_id": 1, "block_uuid": "load_order_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 1 (block_uuid: load_order_data) completes.", "timestamp": 1731069288.135604, "uuid": "328b105aa2a2432f83f4c8271aefe2e1"}
2024-11-08T12:34:49 {"block_run_id": 3, "block_uuid": "load_marketing_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 3 (block_uuid: load_marketing_data) completes.", "timestamp": 1731069289.497287, "uuid": "467a6dd045344b438a2ee72e3fd4ef14"}
2024-11-08T12:34:56 {"cpu": 0.09765625, "cpu_total": 16, "cpu_usage": 0.006103515625, "memory": 2573.0, "memory_total": 9688.0, "memory_usage": 0.2655862923203964, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1731069296.135692, "uuid": "69bf6507884842fca4741d2ad2976421"}
2024-11-08T12:34:56 {"block_run_id": 2, "block_uuid": "export_order_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 2: pipeline retail_pipeline block export_order_data", "timestamp": 1731069296.349749, "uuid": "058af2a022234bfcafc2b5bbbd99df34"}
2024-11-08T12:34:57 {"block_run_id": 4, "block_uuid": "export_marketing_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 4: pipeline retail_pipeline block export_marketing_data", "timestamp": 1731069297.388686, "uuid": "77879fb2454842f3a4d2ce360c808abe"}
2024-11-08T12:34:57 {"block_run_id": 5, "block_uuid": "transform_order_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 5: pipeline retail_pipeline block transform_order_data", "timestamp": 1731069297.410802, "uuid": "20bb79984cf24aa79b1bef47e58f35fc"}
2024-11-08T12:34:57 {"block_run_id": 6, "block_uuid": "transform_marketing_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 6: pipeline retail_pipeline block transform_marketing_data", "timestamp": 1731069297.43045, "uuid": "8d4dd5c77b394e7f963c034106b08516"}
2024-11-08T12:34:57 {"block_run_id": 2, "block_uuid": "export_order_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 2 (block_uuid: export_order_data) completes.", "timestamp": 1731069297.843886, "uuid": "5e5cc3cd2565453985cee598a4f3ba96"}
2024-11-08T12:34:58 {"block_run_id": 6, "block_uuid": "transform_marketing_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 6 (block_uuid: transform_marketing_data) completes.", "timestamp": 1731069298.202323, "uuid": "e145bcf6460d469a91bbba1fe9f47bd5"}
2024-11-08T12:34:58 {"block_run_id": 5, "block_uuid": "transform_order_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 5 (block_uuid: transform_order_data) completes.", "timestamp": 1731069298.245421, "uuid": "1ba26d1129104cb289903fa69c89cac8"}
2024-11-08T12:34:59 {"block_run_id": 4, "block_uuid": "export_marketing_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 4 (block_uuid: export_marketing_data) completes.", "timestamp": 1731069299.01503, "uuid": "8dc7cf5ed1af4b61b69fe79e272b05fa"}
2024-11-08T12:35:06 {"cpu": 0.095703125, "cpu_total": 16, "cpu_usage": 0.0059814453125, "memory": 2575.0, "memory_total": 9688.0, "memory_usage": 0.2657927332782824, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1731069306.527863, "uuid": "495782dd932d4598bf41de59ec9bec98"}
2024-11-08T12:35:06 {"block_run_id": 7, "block_uuid": "merge_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 7: pipeline retail_pipeline block merge_data", "timestamp": 1731069306.716073, "uuid": "e6dfd0f51859487ba1dc7a345263462d"}
2024-11-08T12:35:08 {"block_run_id": 7, "block_uuid": "merge_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 7 (block_uuid: merge_data) completes.", "timestamp": 1731069308.048954, "uuid": "56618710afae43c499f42f0f87aee80d"}
2024-11-08T12:35:16 {"cpu": 0.09375, "cpu_total": 16, "cpu_usage": 0.005859375, "memory": 2569.0, "memory_total": 9688.0, "memory_usage": 0.2651734104046243, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1731069316.741556, "uuid": "cefea40da4cd4fc5b49525351b172bc2"}
2024-11-08T12:35:16 {"block_run_id": 8, "block_uuid": "export_biqquery", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 8: pipeline retail_pipeline block export_biqquery", "timestamp": 1731069316.935491, "uuid": "e15875e363874047b1e7e604f1189f16"}
2024-11-08T12:35:18 {"block_run_id": 8, "block_uuid": "export_biqquery", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "EXCEPTION", "message": "BlockRun 8 (block_uuid: export_biqquery) failed.", "timestamp": 1731069318.692333, "uuid": "cf819c5c6b4f47f987f071bc8e33587d", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 354, in export\n    __process(database=database, write_disposition=write_disposition)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 248, in __process\n    df_existing = self.client.query(f\"\"\"\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 3387, in query\n    return _job_helpers.query_jobs_insert(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 158, in query_jobs_insert\n    future = do_query()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 135, in do_query\n    query_job._begin(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1379, in _begin\n    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 723, in _begin\n    api_response = client._call_api(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 818, in _call_api\n    return call()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/_http/__init__.py\", line 494, in api_request\n    raise exceptions.from_http_response(response)\ngoogle.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/hardytec-demo-projects/jobs?prettyPrint=false: Location DE does not support this operation.\n\nLocation: DE\nJob ID: 90d9e606-5f0a-4ed5-831c-a78f2abc6bdf\n\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 800, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1731, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1236, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "400 POST https://bigquery.googleapis.com/bigquery/v2/projects/hardytec-demo-projects/jobs?prettyPrint=false: Location DE does not support this operation.\n\nLocation: DE\nJob ID: 90d9e606-5f0a-4ed5-831c-a78f2abc6bdf\n"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 354, in export
    __process(database=database, write_disposition=write_disposition)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 248, in __process
    df_existing = self.client.query(f"""
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 3387, in query
    return _job_helpers.query_jobs_insert(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py", line 158, in query_jobs_insert
    future = do_query()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py", line 135, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1379, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 723, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 818, in _call_api
    return call()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/hardytec-demo-projects/jobs?prettyPrint=false: Location DE does not support this operation.

Location: DE
Job ID: 90d9e606-5f0a-4ed5-831c-a78f2abc6bdf

2024-11-08T12:35:26 {"cpu": 0.091796875, "cpu_total": 16, "cpu_usage": 0.0057373046875, "memory": 2574.0, "memory_total": 9688.0, "memory_usage": 0.2656895127993394, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 1 in schedule 1 is alive.", "timestamp": 1731069326.964239, "uuid": "66c69b9e9bdf4f039273c809a7b810d8"}
