2024-11-08T12:47:08 {"cpu": 0.07177734375, "cpu_total": 16, "cpu_usage": 0.004486083984375, "memory": 2880.0, "memory_total": 9688.0, "memory_usage": 0.2972749793559042, "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 2 in schedule 2 is alive.", "timestamp": 1731070028.701569, "uuid": "92487e0fe4d04fe78965d1054a7e2cb1"}
2024-11-08T12:47:08 {"block_run_id": 9, "block_uuid": "load_order_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 9: pipeline retail_pipeline block load_order_data", "timestamp": 1731070028.914252, "uuid": "3f68febd4fb34256b070d0bd620466cb"}
2024-11-08T12:47:08 {"cpu": 0.07177734375, "cpu_total": 16, "cpu_usage": 0.004486083984375, "memory": 2917.0, "memory_total": 9688.0, "memory_usage": 0.30109413707679605, "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 2 in schedule 2 is alive.", "timestamp": 1731070028.914564, "uuid": "90b8be19741045139c5db870fabc405d"}
2024-11-08T12:47:09 {"block_run_id": 11, "block_uuid": "load_marketing_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 11: pipeline retail_pipeline block load_marketing_data", "timestamp": 1731070029.962262, "uuid": "ae39e83f5b5e478f933727df7c57495e"}
2024-11-08T12:47:10 {"block_run_id": 9, "block_uuid": "load_order_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 9 (block_uuid: load_order_data) completes.", "timestamp": 1731070030.11068, "uuid": "ea9afcdbda604713bd2fbb48d733fbe4"}
2024-11-08T12:47:11 {"block_run_id": 11, "block_uuid": "load_marketing_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 11 (block_uuid: load_marketing_data) completes.", "timestamp": 1731070031.289365, "uuid": "4bbbda10b9ea4246841a3da02187faa3"}
2024-11-08T12:47:19 {"cpu": 0.07080078125, "cpu_total": 16, "cpu_usage": 0.004425048828125, "memory": 2873.0, "memory_total": 9688.0, "memory_usage": 0.29655243600330305, "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 2 in schedule 2 is alive.", "timestamp": 1731070039.06395, "uuid": "a79e5e37dcd147c6a84f962a6cd514e7"}
2024-11-08T12:47:19 {"block_run_id": 10, "block_uuid": "export_order_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 10: pipeline retail_pipeline block export_order_data", "timestamp": 1731070039.247196, "uuid": "54d67d7d00a74e889a007635dc33412a"}
2024-11-08T12:47:20 {"block_run_id": 12, "block_uuid": "export_marketing_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 12: pipeline retail_pipeline block export_marketing_data", "timestamp": 1731070040.280544, "uuid": "f81083aabe734d0d902847ec5e48535e"}
2024-11-08T12:47:20 {"block_run_id": 14, "block_uuid": "transform_marketing_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 14: pipeline retail_pipeline block transform_marketing_data", "timestamp": 1731070040.297967, "uuid": "3ef565c08ce14f6182863e070b5d92fc"}
2024-11-08T12:47:20 {"block_run_id": 13, "block_uuid": "transform_order_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 13: pipeline retail_pipeline block transform_order_data", "timestamp": 1731070040.310721, "uuid": "3c89aa42b6684df295359ce588438303"}
2024-11-08T12:47:20 {"block_run_id": 10, "block_uuid": "export_order_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 10 (block_uuid: export_order_data) completes.", "timestamp": 1731070040.423609, "uuid": "826e544712464612ae539cb1217cf633"}
2024-11-08T12:47:20 {"block_run_id": 14, "block_uuid": "transform_marketing_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 14 (block_uuid: transform_marketing_data) completes.", "timestamp": 1731070040.854563, "uuid": "ce877f0f823d4fbba8d04e41f513af6e"}
2024-11-08T12:47:20 {"block_run_id": 13, "block_uuid": "transform_order_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 13 (block_uuid: transform_order_data) completes.", "timestamp": 1731070040.915891, "uuid": "e99f072115854d97a27c26bec2a9a1b9"}
2024-11-08T12:47:21 {"block_run_id": 12, "block_uuid": "export_marketing_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 12 (block_uuid: export_marketing_data) completes.", "timestamp": 1731070041.442678, "uuid": "5ae71eaa2e1f4b208e7282830b04194d"}
2024-11-08T12:47:28 {"cpu": 0.08154296875, "cpu_total": 16, "cpu_usage": 0.005096435546875, "memory": 2876.0, "memory_total": 9688.0, "memory_usage": 0.29686209744013214, "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 2 in schedule 2 is alive.", "timestamp": 1731070048.406166, "uuid": "5e6eaf3a99454ba5a58627e365486298"}
2024-11-08T12:47:28 {"block_run_id": 15, "block_uuid": "merge_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 15: pipeline retail_pipeline block merge_data", "timestamp": 1731070048.601652, "uuid": "25856d79385b47d2a7b50309dd1f1fcb"}
2024-11-08T12:47:29 {"block_run_id": 15, "block_uuid": "merge_data", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 15 (block_uuid: merge_data) completes.", "timestamp": 1731070049.790414, "uuid": "06fa86e1880642acb1f50d9e4a6ec481"}
2024-11-08T12:47:38 {"cpu": 0.08056640625, "cpu_total": 16, "cpu_usage": 0.005035400390625, "memory": 2870.0, "memory_total": 9688.0, "memory_usage": 0.29624277456647397, "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 2 in schedule 2 is alive.", "timestamp": 1731070058.629754, "uuid": "19f8d9ef14224555b4d3d6e4017f9588"}
2024-11-08T12:47:38 {"block_run_id": 16, "block_uuid": "export_biqquery", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 16: pipeline retail_pipeline block export_biqquery", "timestamp": 1731070058.823924, "uuid": "8f100bff57ba414885343aea7f7cf27f"}
2024-11-08T12:47:39 {"block_run_id": 17, "block_uuid": "export_merged_data_bucket", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 17: pipeline retail_pipeline block export_merged_data_bucket", "timestamp": 1731070059.860752, "uuid": "b3274459a308426d907f9ea804c1e5d6"}
2024-11-08T12:47:40 {"block_run_id": 16, "block_uuid": "export_biqquery", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "EXCEPTION", "message": "BlockRun 16 (block_uuid: export_biqquery) failed.", "timestamp": 1731070060.862239, "uuid": "8ab06a7fa32747a5b1995faa23437bb1", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 354, in export\n    __process(database=database, write_disposition=write_disposition)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 248, in __process\n    df_existing = self.client.query(f\"\"\"\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 3387, in query\n    return _job_helpers.query_jobs_insert(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 158, in query_jobs_insert\n    future = do_query()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py\", line 135, in do_query\n    query_job._begin(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1379, in _begin\n    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 723, in _begin\n    api_response = client._call_api(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 818, in _call_api\n    return call()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/_http/__init__.py\", line 494, in api_request\n    raise exceptions.from_http_response(response)\ngoogle.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/hardytec-demo-projects/jobs?prettyPrint=false: Location DE does not support this operation.\n\nLocation: DE\nJob ID: 5683ddf0-bbd1-4ed7-9f03-ca7dcfffb4ca\n\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 800, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1731, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1236, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "400 POST https://bigquery.googleapis.com/bigquery/v2/projects/hardytec-demo-projects/jobs?prettyPrint=false: Location DE does not support this operation.\n\nLocation: DE\nJob ID: 5683ddf0-bbd1-4ed7-9f03-ca7dcfffb4ca\n"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 354, in export
    __process(database=database, write_disposition=write_disposition)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 248, in __process
    df_existing = self.client.query(f"""
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 3387, in query
    return _job_helpers.query_jobs_insert(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py", line 158, in query_jobs_insert
    future = do_query()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_job_helpers.py", line 135, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1379, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 723, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 818, in _call_api
    return call()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/hardytec-demo-projects/jobs?prettyPrint=false: Location DE does not support this operation.

Location: DE
Job ID: 5683ddf0-bbd1-4ed7-9f03-ca7dcfffb4ca

2024-11-08T12:47:41 {"block_run_id": 17, "block_uuid": "export_merged_data_bucket", "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 17 (block_uuid: export_merged_data_bucket) completes.", "timestamp": 1731070061.480474, "uuid": "8de10cbf9d3f473787fa13da563df4b9"}
2024-11-08T12:47:48 {"cpu": 0.08544921875, "cpu_total": 16, "cpu_usage": 0.005340576171875, "memory": 2885.0, "memory_total": 9688.0, "memory_usage": 0.2977910817506193, "pipeline_run_id": 2, "pipeline_schedule_id": 2, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 2 in schedule 2 is alive.", "timestamp": 1731070068.901925, "uuid": "9d2f4ceab952449f856e658e601f5f80"}
